typography_spectrum: 0.5
content_rating:
  adult: false
color:
  lightness: 0.09097869696351203
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  saturation: 0.560197379104839
  brandStrength: 0.6766742997981315
  rhythmicContrast: 0.9077085465909235
github: true
opengraph: {}
layout_spectrum: 0.5
analytics: {}
author:
  name: Wendy Pappas
  url: www.totallywellin.com
  email: wendy@totallywellwithin.com
name: TotallyWellWithin.com
navigation:
  - name: 'Colonic hydration, cleansing and supplementation.'
    url: 'https://www.totallywellwithin.com'
    type: external
title: 'Check your Reserves '
content: []
description: 'Find out what deficiencies might be impacting your bottom line. '
purpose:
  - type: contact
    url: 'tel:9492784600'
    label: Call 9492784600
  - type: external
    url: 'http://www.totallywellwithin.com'
    label: 'http://www.totallywellwithin.com'
