name: TotallyWellWithin.com
analytics: {}
content_rating:
  adult: false
github: true
description: 'Find out what deficiencies might be impacting your bottom line. '
opengraph: {}
title: 'Check your Reserves '
author:
  name: Wendy Pappas
  url: www.totallywellin.com
  email: wendy@totallywellwithin.com
color:
  lightness: 0.09097869696351203
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  saturation: 0.560197379104839
  brandStrength: 0.6766742997981315
  rhythmicContrast: 0.9077085465909235
content: []
layout_spectrum: 0.5
typography_spectrum: 0.5
